# Generated by Django 3.1.4 on 2021-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20210915_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='cantidad_tipo',
            field=models.CharField(choices=[('Toneladas', 'Toneladas'), ('Tarimas', 'Tarimas'), ('Otro', 'Otro')], default=None, max_length=30),
        ),
    ]
