# Generated by Django 3.1.4 on 2021-09-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_viajes_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes_viajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('recoleccion', 'Recoleccion'), ('Entrega', 'Entrega'), ('Otro', 'Otro')], default=None, max_length=30)),
                ('imagen', models.ImageField(upload_to='imagenes-fletes/')),
                ('flete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.viajes')),
            ],
        ),
    ]
