# Generated by Django 3.1.4 on 2021-09-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20210921_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_viajes',
            name='categoria',
            field=models.CharField(choices=[('Recoleccion', 'Recoleccion'), ('Entrega', 'Entrega'), ('Otro', 'Otro')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='status',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='0', max_length=30),
        ),
    ]
