# Generated by Django 3.1.4 on 2021-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20210921_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='cantidad_tipo',
            field=models.CharField(choices=[('Toneladas', 'Toneladas'), ('Tarimas', 'Tarimas'), ('Otro', 'Otro')], default='Otro', max_length=30),
        ),
    ]
