# Generated by Django 3.1.4 on 2021-09-22 18:41

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20210921_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_viajes',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to=leads.models.Imagenes_viajes.photopath),
        ),
    ]
