# Generated by Django 3.1.4 on 2021-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20210922_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flete_id', models.CharField(max_length=10)),
                ('metodo_contacto', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=150)),
            ],
        ),
    ]
