# Generated by Django 3.1.4 on 2021-09-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_auto_20210928_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rfc', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('cp', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='operador',
            name='linea_de_transporte',
        ),
        migrations.AddField(
            model_name='operador',
            name='linea_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lineatransporte'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='linea_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lineatransporte'),
        ),
    ]
