# Generated by Django 3.1.4 on 2021-09-28 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_auto_20210928_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes_viajes',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 14, 30, 23, 557497)),
        ),
    ]
