# Generated by Django 3.1.4 on 2021-09-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_auto_20210928_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineatransporte',
            name='ciudad',
            field=models.CharField(default='Tepex', max_length=20),
            preserve_default=False,
        ),
    ]
