# Generated by Django 3.1.4 on 2021-09-28 14:58

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_lineatransporte_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='id',
            field=models.CharField(default=leads.models.Viajes.pk_generator, max_length=10, primary_key=True, serialize=False),
        ),
    ]
