# Generated by Django 3.1.4 on 2021-09-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_auto_20210928_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='costo',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
