# Generated by Django 3.1.4 on 2021-09-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_viajes_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viajes',
            name='linea_transporte',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='operador',
        ),
    ]
