# Generated by Django 3.1.4 on 2021-09-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_auto_20210930_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
