# Generated by Django 3.1.4 on 2021-09-30 15:22

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_auto_20210930_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='linea_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lineatransporte'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.operador'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='id',
            field=models.CharField(default=leads.models.Viajes.pk_generator, max_length=10, primary_key=True, serialize=False),
        ),
    ]
