# Generated by Django 3.1.4 on 2021-10-01 13:58

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_auto_20210930_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('Transportista', 'Quiero enviar mi mercancia con Flit'), ('Embarcador', 'Quiero trabajar como transportista en Flit')], default=None, max_length=50)),
                ('compania', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='viajes',
            name='id',
            field=models.CharField(default=leads.models.Viajes.pk_generator, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
