# Generated by Django 3.1.4 on 2021-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_auto_20211001_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistro',
            name='rol',
            field=models.CharField(choices=[('Transportista', 'Transportista'), ('Embarcador', 'Embarcador')], default=None, max_length=50),
        ),
    ]
