# Generated by Django 3.1.4 on 2021-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_auto_20211013_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='cantidad_tipo',
            field=models.CharField(choices=[('Toneladas', 'Toneladas'), ('Tarimas', 'Tarimas'), ('Piezas', 'Piezas'), ('Bultos', 'Bultos'), ('Piezas', 'Piezas'), ('Otro', 'Otro')], default='Otro', max_length=30),
        ),
    ]
