# Generated by Django 3.1.4 on 2021-11-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_auto_20211113_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajes',
            old_name='f_salida',
            new_name='f_creacion',
        ),
        migrations.AddField(
            model_name='viajes',
            name='f_recoleccion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
